version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install --user -r requirements.txt
      - run: python app/manage.py test

workflows:
  tests-workflow:
    jobs:
      - tests